name: WORKIT Builder

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
          arguments: ''
